name: agenta-oss-gh

services:
    web:
        profiles:
            - with-web

        # build:
        #     context: ../../../web
        #     dockerfile: oss/docker/Dockerfile.gh

        image: ghcr.io/agenta-ai/${AGENTA_WEB_IMAGE_NAME:-agenta-web}:${AGENTA_WEB_IMAGE_TAG:-latest}

        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        networks:
            - agenta-oss-gh-network
        labels:
            - "traefik.http.routers.web.rule=PathPrefix(`/`)"
            - "traefik.http.routers.web.entrypoints=web"
            - "traefik.http.services.web.loadbalancer.server.port=3000"
            - "traefik.enable=false"

        command: sh -c "node ./oss/server.js"
        restart: always

    api:
        build:
            context: ../../../api
            dockerfile: oss/docker/Dockerfile.gh

        image: ghcr.io/agenta-ai/${AGENTA_API_IMAGE_NAME:-agenta-api}:${AGENTA_API_IMAGE_TAG:-latest}

        networks:
            - agenta-oss-gh-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:
            - "traefik.http.routers.api.rule=PathPrefix(`/api/`)"
            - "traefik.http.routers.api.entrypoints=web"
            - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
            - "traefik.http.middlewares.api-strip.stripprefix.forceslash=true"
            - "traefik.http.routers.api.middlewares=api-strip"
            - "traefik.http.services.api.loadbalancer.server.port=8000"
            - "traefik.http.routers.api.service=api"
            - "traefik.enable=false"

        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        command: [ "uvicorn", "entrypoint:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--root-path", "/api" ]

        depends_on:
            postgres:
                condition: service_healthy
            alembic:
                condition: service_completed_successfully
        restart: always

    worker:
        build:
            context: ../../../api
            dockerfile: oss/docker/Dockerfile.gh

        image: ghcr.io/agenta-ai/${AGENTA_API_IMAGE_NAME:-agenta-api}:${AGENTA_API_IMAGE_TAG:-latest}

        networks:
            - agenta-oss-gh-network
        extra_hosts:
            - "host.docker.internal:host-gateway"

        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        command: >
            celery -A entrypoint.celery_app worker --concurrency=1 --max-tasks-per-child=1 --prefetch-multiplier=1

        depends_on:
            - postgres
            - rabbitmq
            - redis
        restart: always

    alembic:
        build:
            context: ../../../api
            dockerfile: oss/docker/Dockerfile.gh

        image: ghcr.io/agenta-ai/${AGENTA_API_IMAGE_NAME:-agenta-api}:${AGENTA_API_IMAGE_TAG:-latest}

        networks:
            - agenta-oss-gh-network

        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        command: sh -c "python -c 'from oss.databases.postgres.migrations.utils import split_core_and_tracing as split; split(); from oss.databases.postgres.migrations.core.utils import run_alembic_migration as run; run(); from oss.databases.postgres.migrations.tracing.utils import run_alembic_migration as run; run(); from oss.databases.postgres.migrations.utils import copy_nodes_from_core_to_tracing as copy; copy();'"

        depends_on:
            postgres:
                condition: service_healthy

    completion:
        build:
            context: ../../../services/completion
            dockerfile: oss/docker/Dockerfile.gh

        image: ghcr.io/agenta-ai/agenta-completion

        networks:
            - agenta-oss-gh-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:
            - "traefik.http.routers.completion.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/services/completion/`)"
            - "traefik.http.routers.completion.entrypoints=web"
            - "traefik.http.middlewares.completion-strip.stripprefix.prefixes=/services/completion"
            - "traefik.http.middlewares.completion-strip.stripprefix.forceslash=true"
            - "traefik.http.routers.completion.middlewares=completion-strip"
            - "traefik.http.services.completion.loadbalancer.server.port=80"
            - "traefik.http.routers.completion.service=completion"
            - "traefik.enable=false"

        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        command: [ "python", "oss/src/main.py" ]

        restart: always

    chat:
        build:
            context: ../../../services/chat
            dockerfile: oss/docker/Dockerfile.gh

        image: ghcr.io/agenta-ai/agenta-chat

        env_file:
            - ${ENV_FILE:-./.env.oss.gh}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:
            - "traefik.http.routers.chat.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/services/chat/`)"
            - "traefik.http.routers.chat.entrypoints=web"
            - "traefik.http.middlewares.chat-strip.stripprefix.prefixes=/services/chat"
            - "traefik.http.middlewares.chat-strip.stripprefix.forceslash=true"
            - "traefik.http.routers.chat.middlewares=chat-strip"
            - "traefik.http.services.chat.loadbalancer.server.port=80"
            - "traefik.http.routers.chat.service=chat"
            - "traefik.enable=false"
            
        networks:
            - agenta-oss-gh-network

        command: [ "python", "oss/src/main.py" ]

        restart: always

    postgres:
        image: postgres:16.2

        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            # optional - leave default DB as 'postgres'
            POSTGRES_DB: postgres

        volumes:
            - postgres-data:/var/lib/postgresql/data/
            - ../../../api/oss/databases/postgres/init-db-oss.sql:/docker-entrypoint-initdb.d/init-db.sql

        restart: always
        networks:
            - agenta-oss-gh-network

        env_file:
            - ${ENV_FILE:-./.env.oss.gh}
        
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres" ]
          interval: 10s
          timeout: 5s
          retries: 10



    rabbitmq:
        image: rabbitmq:3-management

        volumes:
            - rabbitmq-data:/var/lib/rabbitmq

        networks:
            - agenta-oss-gh-network

        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        restart: always

    redis:
        image: redis:latest

        volumes:
            - redis-data:/data

        networks:
            - agenta-oss-gh-network

        restart: always

    cache:
        image: redis:latest

        command: >
            redis-server --port 6378 --appendonly no --appendfsync no --save "" --maxmemory 128mb --maxmemory-policy allkeys-lru


        volumes:
            - cache-data:/data

        networks:
            - agenta-oss-gh-network

        labels:
            - "traefik.enable=false"

        restart: always

        healthcheck:
            test: [ "CMD", "redis-cli", "-p", "6378", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s



    nginx:
      image: nginx:latest
      profiles:
        - with-nginx
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      env_file:
        - ${ENV_FILE:-./.env.oss.gh}
      networks:
        - agenta-oss-gh-network
        - dokploy-network
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.agenta.rule=Host(`${TRAEFIK_DOMAIN}`)"
        - "traefik.http.routers.agenta.entrypoints=websecure"
        - "traefik.http.routers.agenta.tls=true"
        - "traefik.http.services.agenta.loadbalancer.server.port=80"
      depends_on:
        - api
        - web
      restart: always



    supertokens:
        image: registry.supertokens.io/supertokens/supertokens-postgresql

        depends_on:
            postgres:
                condition: service_healthy

        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        environment:
            POSTGRESQL_CONNECTION_URI: ${POSTGRES_URI_SUPERTOKENS}

        networks:
            - agenta-oss-gh-network
        healthcheck:
            test: >
                bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
            interval: 10s
            timeout: 5s
            retries: 5
        restart: always

networks:
    agenta-oss-gh-network:
    dokploy-network:
        external: true

volumes:
    postgres-data:
    rabbitmq-data:
    redis-data:
    cache-data:
